### ISSUE TITLE
Incomplete Submission

### ISSUE THREAD

**Issue by Caealana** [AdamKinnane/intro-data-capstone-biodiversity#1]
Hi @AdamKinnane! If you completed this biodiversity project in the Codecademy environment, you should submit a .pdf file of the powerpoint presentation you put together to be graded. Let me know if you have any questions about this!

**Comment by AdamKinnane** [comment]
Hi @Caealana I uploaded both a couple of weeks ago when I finished! Not sure what happened here but will upload again now but have also attached here just in case. Thanks! 
[Adam Kinnan Keynote-Biodiversity for the National Parks.pdf](https://github.com/AdamKinnane/intro-data-capstone-biodiversity/files/1831701/Adam.Kinnan.Keynote-Biodiversity.for.the.National.Parks.pdf)

**Comment by AdamKinnane** [comment]
@Caealana i received an email saying "Your project has been reviewed! One of our reviewers has left you an overall summary of how you did plus specific comments on your code — all on GitHub." however I cannot see it in git? Can you please let me know if it has been added?

**Comment by Caealana** [comment]
Hi @AdamKinnane! I apologize for the confusion. It looks like I mistakenly marked your project as reviewed because I thought another advisor had left comments. I will review your project and leave a comment here once I am finished. Thank you for your patience!

**Comment by Caealana** [comment]
Hi again, @AdamKinnane. I have graded your work. Great job on your project!
